const modal = document.querySelector('#modal');
const content = document.querySelector('#modalContent');
let timerId, seconds = 25 * 60;

const templates = {
  pomodoro: () => `<h2>沉浸番茄钟</h2><p>专注 25 分钟，然后好好休息 5 分钟。</p><div class="timer" id="timer">25:00</div><div class="timer-actions"><button class="primary" id="timerStart">开始专注</button><button class="secondary" id="timerReset">重置</button></div>`,
  qr: () => `<h2>二维码生成器</h2><p>输入任意内容，生成可保存的二维码链接。</p><input id="qrInput" placeholder="粘贴链接或输入文字" /><button class="primary" id="qrButton">生成二维码</button><div class="result" id="qrResult" style="display:none"></div>`,
  text: () => `<h2>文本整理</h2><p>自动移除多余空行，并清理每一行开头与结尾的空格。</p><textarea id="textInput" placeholder="把需要整理的文字放在这里…"></textarea><button class="primary" id="textButton">整理并复制</button><div class="result" id="textResult" style="display:none"></div>`,
  convert: () => `<h2>单位换算</h2><p>选一个单位，输入数字，即刻转换。</p><select id="unit"><option value="km">公里 → 英里</option><option value="kg">千克 → 磅</option><option value="c">摄氏度 → 华氏度</option></select><input id="convertInput" type="number" placeholder="输入数值" /><button class="primary" id="convertButton">开始换算</button><div class="result" id="convertResult" style="display:none"></div>`,
  random: () => `<h2>随机决定</h2><p>每行写一个选项，让一点随机带你跳出犹豫。</p><textarea id="randomInput" placeholder="看电影\n去散步\n读一本书"></textarea><button class="primary" id="randomButton">替我选择</button><div class="result" id="randomResult" style="display:none"></div>`
};

function openTool(name) { content.innerHTML = templates[name](); modal.classList.add('open'); if (name === 'pomodoro') bindTimer(); if (name === 'qr') bindQr(); if (name === 'text') bindText(); if (name === 'convert') bindConvert(); if (name === 'random') bindRandom(); }
function bindTimer() { const display = document.querySelector('#timer'); const draw = () => display.textContent = `${String(Math.floor(seconds / 60)).padStart(2,'0')}:${String(seconds % 60).padStart(2,'0')}`; draw(); document.querySelector('#timerStart').onclick = e => { if (timerId) { clearInterval(timerId); timerId = null; e.target.textContent = '继续专注'; return; } e.target.textContent = '暂停'; timerId = setInterval(() => { seconds--; draw(); if (!seconds) { clearInterval(timerId); timerId = null; e.target.textContent = '完成啦！'; } }, 1000); }; document.querySelector('#timerReset').onclick = () => { clearInterval(timerId); timerId = null; seconds = 25 * 60; draw(); document.querySelector('#timerStart').textContent = '开始专注'; }; }
function bindQr() { document.querySelector('#qrButton').onclick = () => { const value = document.querySelector('#qrInput').value.trim(); const result = document.querySelector('#qrResult'); if (!value) return; result.style.display = 'block'; result.innerHTML = `已准备好：<a target="_blank" href="https://api.qrserver.com/v1/create-qr-code/?size=180x180&data=${encodeURIComponent(value)}">打开二维码</a>`; }; }
function bindText() { document.querySelector('#textButton').onclick = async () => { const value = document.querySelector('#textInput').value.trim().split('\n').map(x => x.trim()).filter(Boolean).join('\n'); const result = document.querySelector('#textResult'); if (!value) return; await navigator.clipboard?.writeText(value); result.style.display = 'block'; result.textContent = '整理完成，已复制到剪贴板。'; }; }
function bindConvert() { document.querySelector('#convertButton').onclick = () => { const n = Number(document.querySelector('#convertInput').value), u = document.querySelector('#unit').value, r = document.querySelector('#convertResult'); if (Number.isNaN(n)) return; const values = { km:[n * .621371,'英里'],kg:[n * 2.20462,'磅'],c:[n * 9/5 + 32,'°F'] }; r.style.display='block'; r.textContent = `${n} = ${values[u][0].toFixed(2)} ${values[u][1]}`; }; }
function bindRandom() { document.querySelector('#randomButton').onclick = () => { const items = document.querySelector('#randomInput').value.split('\n').map(x=>x.trim()).filter(Boolean); const r = document.querySelector('#randomResult'); if (!items.length) return; r.style.display='block'; r.innerHTML = `今天就选：<strong>${items[Math.floor(Math.random()*items.length)]}</strong>`; }; }
document.querySelectorAll('[data-tool]').forEach(button => button.onclick = () => openTool(button.dataset.tool));
document.querySelector('#closeModal').onclick = () => { modal.classList.remove('open'); clearInterval(timerId); timerId=null; };
modal.onclick = e => { if (e.target === modal) document.querySelector('#closeModal').click(); };
document.querySelector('#search').oninput = e => { const query=e.target.value.toLowerCase(); let count=0; document.querySelectorAll('.tool-card').forEach(card=>{const match=card.dataset.name.includes(query);card.style.display=match?'flex':'none'; if(match) count++;}); document.querySelector('#noResult').style.display=count?'none':'block'; };
document.querySelectorAll('[data-query]').forEach(button => button.onclick = () => { const input=document.querySelector('#search'); input.value=button.dataset.query; input.dispatchEvent(new Event('input')); });
document.querySelector('#themeToggle').onclick = () => { document.body.classList.toggle('dark'); document.querySelector('#themeToggle').textContent=document.body.classList.contains('dark')?'☀':'☾'; };
document.addEventListener('keydown', e => { if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase()==='k') { e.preventDefault(); document.querySelector('#search').focus(); } if (e.key==='Escape') document.querySelector('#closeModal').click(); });

